import React, { useEffect } from 'react'
import Head from 'next/head'
import { useSelector, useDispatch } from 'react-redux'
import Login from '../components/Login'
import { auth } from '../firebase'
import { useRouter } from 'next/router'

export default function Home() {
  const user = useSelector(State => State.User)
  const dispatch = useDispatch()
  const router = useRouter()
  console.log(user);

  useEffect(() => {
    auth.onAuthStateChanged(user => {
      if (user) {
        dispatch({
          type: 'Add_User',
          user: user
        })
        router.push('/Home')
      } else {
        dispatch({
          type: 'Sign_Out',
          user: null
        })
        router.push('/')
      }
    })
  }, [])


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />

    </div>
  )
}
